### ISSUE TITLE
Oneplus 5 installation

### ISSUE THREAD

**Issue by karencho777** [Magisk-Modules-Repo/KaliNethunter#13]
Hello have oneplus 5 with the latest updates, was trying to install but it did not install the apk files.. so i did it manually then install chroot manually too ... not when i am using the Nethnter Terminal and want to turn on for example Msfconsole it giving me an error about that file is not exist plus when i am trying to turn on terminal as Kali user it is just turning off... 

 here is an install

- Copying zip to temp directory
- Installing KaliNethunter-v8.2(22).zip
- Device is system-as-root
Archive:  /data/user/0/com.R.RUvoeK.a.J.lTE/cache/flash/install.zip
  inflating: module.prop
Archive:  /data/user/0/com.R.RUvoeK.a.J.lTE/cache/flash/install.zip
  inflating: install.sh
  inflating: module.prop
 
##################################################
################### NetHunter ####################
         ******************************
         Powered by Magisk (@topjohnwu)
         ******************************
 
mount: can't read '/etc/fstab': No such file or directory
mount: can't read '/etc/fstab': No such file or directory
mount: can't read '/etc/fstab': No such file or directory
 
Extracting files...
Archive:  /data/user/0/com.R.RUvoeK.a.J.lTE/cache/flash/install.zip
   creating: META-INF/
   creating: META-INF/com/
   creating: META-INF/com/google/
   creating: META-INF/com/google/android/
  inflating: META-INF/com/google/android/update-binary
  inflating: META-INF/com/google/android/updater-script
  inflating: .gitattributes
  inflating: README.md
   creating: apps/
  inflating: apps/Term-nh.apk
  inflating: apps/VNC-nh.apk
  inflating: apps/nethunter.apk
  inflating: busybox-amd64
  inflating: busybox-arm
  inflating: busybox-arm64
  inflating: busybox-i386
  inflating: install.sh
  inflating: module.prop
   creating: system/
   creating: system/etc/
   creating: system/etc/firmware/
  inflating: system/etc/firmware/ar7010.fw
  inflating: system/etc/firmware/ar7010_1_1.fw
   creating: system/etc/firmware/ath9k_htc/
  inflating: system/etc/firmware/ath9k_htc/htc_7010-1.4.0.fw
  inflating: system/etc/firmware/ath9k_htc/htc_9271-1.4.0.fw
   creating: system/etc/firmware/brcm/
  inflating: system/etc/firmware/brcm/bcm43xx-0.fw
  inflating: system/etc/firmware/brcm/bcm43xx_hdr-0.fw
  inflating: system/etc/firmware/carl9170-1.fw
  inflating: system/etc/firmware/htc_9271.fw
  inflating: system/etc/firmware/mt7601u.bin
  inflating: system/etc/firmware/rt2561.bin
  inflating: system/etc/firmware/rt2561s.bin
  inflating: system/etc/firmware/rt2661.bin
  inflating: system/etc/firmware/rt2860.bin
  inflating: system/etc/firmware/rt2870.bin
  inflating: system/etc/firmware/rt3070.bin
  inflating: system/etc/firmware/rt3071.bin
  inflating: system/etc/firmware/rt3290.bin
  inflating: system/etc/firmware/rt73.bin
   creating: system/etc/firmware/rtlwifi/
  inflating: system/etc/firmware/rtlwifi/rtl8188eufw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cfw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cfwU.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cfwU_B.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cufw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cufw_A.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cufw_B.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cufw_TMSC.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192defw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192eefw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192eu_nic.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192sefw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8821aefw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8821aefw_wowlan.bin
 
Installing...
Using architecture: arm64
Using path: /data/adb/modules_update/KaliNethunter/system/xbin
avc:  denied  { read } for  scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=file permissive=0
System server has no access to read file context u:object_r:device:s0 (from path /dev/tmp/KaliNethunter/apps/Term-nh.apk, context u:r:system_server:s0)
Error: Unable to open file: apps/Term-nh.apk
Consider using a file under /data/local/tmp/
Error: Can't open file: apps/Term-nh.apk

Exception occurred while executing:
java.lang.IllegalArgumentException: Error: Can't open file: apps/Term-nh.apk
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:466)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1065)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:174)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22694)
	at android.os.Binder.shellCommand(Binder.java:892)
	at android.os.Binder.onTransact(Binder.java:776)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4883)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4249)
	at android.os.Binder.execTransactInternal(Binder.java:1032)
	at android.os.Binder.execTransact(Binder.java:1005)
avc:  denied  { read } for  scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=file permissive=0
System server has no access to read file context u:object_r:device:s0 (from path /dev/tmp/KaliNethunter/apps/VNC-nh.apk, context u:r:system_server:s0)
Error: Unable to open file: apps/VNC-nh.apk
Consider using a file under /data/local/tmp/
Error: Can't open file: apps/VNC-nh.apk

Exception occurred while executing:
java.lang.IllegalArgumentException: Error: Can't open file: apps/VNC-nh.apk
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:466)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1065)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:174)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22694)
	at android.os.Binder.shellCommand(Binder.java:892)
	at android.os.Binder.onTransact(Binder.java:776)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4883)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4249)
	at android.os.Binder.execTransactInternal(Binder.java:1032)
	at android.os.Binder.execTransact(Binder.java:1005)
avc:  denied  { read } for  scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=file permissive=0
System server has no access to read file context u:object_r:device:s0 (from path /dev/tmp/KaliNethunter/apps/nethunter.apk, context u:r:system_server:s0)
Error: Unable to open file: apps/nethunter.apk
Consider using a file under /data/local/tmp/
Error: Can't open file: apps/nethunter.apk

Exception occurred while executing:
java.lang.IllegalArgumentException: Error: Can't open file: apps/nethunter.apk
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:466)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1065)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:174)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22694)
	at android.os.Binder.shellCommand(Binder.java:892)
	at android.os.Binder.onTransact(Binder.java:776)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4883)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4249)
	at android.os.Binder.execTransactInternal(Binder.java:1032)
	at android.os.Binder.execTransact(Binder.java:1005)
cp: can't create directory '/system/etc/firmware/rtlwifi': Read-only file system
cp: can't create '/system/etc/firmware/rt73.bin': Read-only file system
cp: can't create '/system/etc/firmware/rt3290.bin': Read-only file system
cp: can't create '/system/etc/firmware/rt3071.bin': Read-only file system
cp: can't create '/system/etc/firmware/rt3070.bin': Read-only file system
cp: can't create '/system/etc/firmware/rt2870.bin': Read-only file system
cp: can't create '/system/etc/firmware/rt2860.bin': Read-only file system
cp: can't create '/system/etc/firmware/rt2661.bin': Read-only file system
cp: can't create '/system/etc/firmware/rt2561s.bin': Read-only file system
cp: can't create '/system/etc/firmware/rt2561.bin': Read-only file system
cp: can't create '/system/etc/firmware/mt7601u.bin': Read-only file system
cp: can't create '/system/etc/firmware/htc_9271.fw': Read-only file system
cp: can't create '/system/etc/firmware/carl9170-1.fw': Read-only file system
cp: can't create directory '/system/etc/firmware/brcm': Read-only file system
cp: can't create directory '/system/etc/firmware/ath9k_htc': Read-only file system
cp: can't create '/system/etc/firmware/ar7010_1_1.fw': Read-only file system
cp: can't create '/system/etc/firmware/ar7010.fw': Read-only file system
 
Cleaning...
 
Creating symlinks...
 
Unmounting...
umount: can't unmount /system: Invalid argument
umount: can't unmount /data: Device or resource busy
umount: can't unmount /cache: Device or resource busy
 
Symlinking...
Cleaning Up...
 
Done!
`

**Comment by karencho777** [comment]
no one can help?

**Comment by Leojangh** [comment]
me too but  I have no error log during installation ,I install it manually but it doesnt work.

**Comment by Leojangh** [comment]
> me too but I have no error log during installation ,I install it manually but it doesnt work.

And I found that the files under /system in the module were not successfully copied to the target directory.
